apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: youtube-dl-nas-deployment
  labels:
    apps: jhslabel-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jhslabel
  template:
    metadata:
      labels:
        app: jhslabel
    spec:
      containers:
      - name: youtube-dl-nas
        image: modenaf360/youtube-dl-nas
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: youtube-dl-nas-deployment-svc
  labels:
    app: youtube-dl-nas-deployment
spec:
  type: NodePort
  ports:
  - name: youtube-dl-nas-deployment-endpoint
    port: 8080
    protocol: TCP
  selector:
    app: jhslabel
---